# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E-SLNrV5TiMNz30Bj-pqAK8SjQfBVlkC
"""

x=5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體的地址是:{id(x)}")